package bookstore.model;

import java.util.ArrayList;
import java.util.List;

public class BookData {

	public static List<Book> getBooks() {
		List<Book> books = new ArrayList<>();

		books.add(new Book("978-3-86490-207-9", "Testgetriebene Entwicklung mit JavaScript", "Sebastian Springer", 43.9, 220, "01.02.2015", "https://locher.ti.bfh.ch/services/assets/books/6390302b07494c6a203d3d9f7887a7441279765e-00-00.jpeg", "Das Handbuch für den professionellen Programmierer", "Sebastian Springer ist Diplom-Informatiker (FH) und arbeitet als JavaScript-Entwickler bei der Mayflower GmbH in München. Neben seiner Tätigkeit als Consultant unterrichtet er als Dozent an der<br>Hochschule Rosenheim. Er ist ausserdem als Autor für verschiedene Fachmagazine und Referent auf Konferenzen zum Thema Web- und JavaScript-Entwicklung tätig."));
		books.add(new Book("978-3-86490-728-9", "JavaScript", "Marijn Haverbeke", 51.9, 488, "12.12.2019", "https://locher.ti.bfh.ch/services/assets/books/62bef8f9bd54e992181fc96e9728d9b56ae12fa4-00-00.jpeg", "Richtig gut programmieren lernen – Von der ersten Codezeile bis zum eigenen Projekt", "Marijn Haverbeke ist ein begeisterter polyglotter Programmierer. Er hat an einer breiten Palette von Softwaresystemen gearbeitet, von Datenbanken über Compiler bis hin zu Editoren. Ausserdem führt er ein kleines Unternehmen rund um seine Open-Source-Projekte."));
		books.add(new Book("978-3-86490-240-6", "JavaScript kinderleicht!", "Nick Morgan", 38.9, 284, "01.06.2015", "https://locher.ti.bfh.ch/services/assets/books/1201a66d312fe7abd7ceec5f4f2b188569da137f-00-00.jpeg", "Einfach programmieren lernen mit der Sprache des Web", "Nick Morgan ist Webentwickler bei Twitter. Er liebt alle Programmiersprachen, hat aber eine besondere Schwäche für JavaScript. Nick und seine Verlobte leben mit ihrem flauschigen Hund Pancake in San Francisco. Seinen Blog findest du auf skilldrick.co.uk."));
		books.add(new Book("978-3-8362-7221-5", "JavaScript", "Ralph Steyer", 36.9, 400, "03.04.2014", "https://locher.ti.bfh.ch/services/assets/books/b9228281eda163753d5ef53a1b5263c7e855f88c-00-00.jpeg", "Die universelle Sprache zur Web-Programmierung", "Diplom-Mathematiker Ralph Steyer arbeitet seit 1996 selbstständig als Fachautor, Fachjournalist, EDV-Dozent und Programmierer. Davor war er einige Jahre Programmierer bei einer grossen Versicherung. In zahlreichen Schulungen und Vorlesungen in Firmen sowie an Akademien und Fachhochschulen gibt er sein Fachwissen weiter und nutzt die dort gewonnenen Kenntnisse für seine Veröffentlichungen."));
		books.add(new Book("978-3-89864-728-1", "JavaScript für Enterprise-Entwickler", "Oliver Ochs", 46.9, 278, "01.05.2012", "https://locher.ti.bfh.ch/services/assets/books/943ad0a8681a8163e0c45d03cc33bb4fa82f1439-00-00.jpeg", "Professionell programmieren im Browser und auf dem Server", "JavaScript ist längst nicht mehr nur für klassische Webprogrammierer interessant. Auch bei der Entwicklung von Unternehmensanwendungen spielt JavaScript eine immer grössere Rolle: Enterprise-Entwickler mit Java- oder .NET-Hintergrund programmieren selbst server- und browserseitig mit JavaScript, oder sie überarbeiten JavaScript-Code, der von Webagenturen erstellt wurde."));
		books.add(new Book("978-3-8362-6825-7", "Schrödinger lernt HTML5, CSS und JavaScript", "Kai Günster", 65.9, 854, "23.11.2018", "https://locher.ti.bfh.ch/services/assets/books/f56562d671bfd16a4cd0931738d3192f321e4e9c-00-00.jpeg", "Das etwas andere Fachbuch. Der volle Durchmarsch für alle, die HTML5, CSS3 und JavaScript lernen wollen", "Drei Sprachen in einem Schrödinger-Band!<br><br>Lerne die Sprachen des Webs von Grund auf<br>Mit Farbkonzept: Lernen – Anwenden – Wiederholen<br>Mobile Layouts, Objekte, GeoLocation, Audio & Video ... alles drin<br><br>Der Bestseller in dritter Auflage. Schrödinger wird Webentwickler! – und Du bist dabei! Zum Glück hat er einen Kumpel, der auf alles eine Antwort parat hat, solange der Kaffee reicht. Zusammen lernt ihr HTML, CSS und JavaScript. "));
		books.add(new Book("978-3-8362-5687-2", "Professionell entwickeln mit JavaScript", "Philip Ackermann", 68, 648, "22.06.2018", "https://locher.ti.bfh.ch/services/assets/books/cd24db931f975b5496f136442a48643f2143fb17-00-00.jpeg", "Design, Patterns und Praxistipps für Enterprise-fähigen Code", "Philip Ackermann ist Master of Science in Computer Science. Am Fraunhofer-Institut für Angewandte Informationstechnologie FIT arbeitet er als Software-Entwickler an Tools zum teilautomatisierten Testen von Web Compliance, z. B. der Barrierefreiheit von Webseiten. Wissenschaftlich befasst er sich ausserdem mit der modellbasierten Simulation und Evaluierung von mobilen und Web 2.0-Anwendungen."));
		books.add(new Book("978-3-7475-0263-1", "JavaScript für Kids", "Hans-Georg Schumann", 34.9, 336, "24.10.2020", "https://locher.ti.bfh.ch/services/assets/books/b58848285471295e035b3343a40c58bac7016330-00-00.jpeg", "Programmieren lernen ohne Vorkenntnisse", "Hans-Georg Schumann war Informatik- und Mathematiklehrer an einer Gesamtschule. Er hat viele erfolgreiche Bücher in der mitp-Buchreihe »... für Kids« geschrieben."));
		//books.add(new Book("978-3-8322-7369-5", "JavaScript für Kids", "Frank Biet", 3, 480, "08.08.2013", "https://locher.ti.bfh.ch/services/assets/books/6b9f05e56e4fe24e6498b47aaf7003596f834452-00-00.jpeg", "-", "Frank Biet arbeitet freiberuflich u.a. als Software-Entwickler und Dozent mit dem Schwerpunkt Multimedia- <br>Programmierung."));
		books.add(new Book("978-3-8391-0738-6", "Einstieg in HTML und Javascript", "Marco Schuchmann", 7.9, 72, "02.11.2012", "https://locher.ti.bfh.ch/services/assets/books/af96453f144cb3f6af2816622e7943af6604e42f-00-00.jpeg", "Mit vielen Beispielen und einfachen Browsergames", "Marco Schuchmann:<br><br>Dr. rer. nat. Marco Schuchmann hat in Darmstadt Mathematik studiert und ist an der Hochschule Darmstadt im Fachbereich Mathematik und Naturwissenschaften angestellt. Hier hält er u.a. Mathematik Vorlesungen über Themen wie z.B. Wavelets und auf dem Gebiet der mathematischen Statistik. Er hat seit 1996 bei diversen Verlagen mathematische Fachbücher veröffentlicht.<br>"));
		books.add(new Book("978-3-464-56150-8", "Web-Seiten mit HTML und JavaScript", "Björn Krebs, Thorsten H. Krebs", 31.9, 160, "15.01.2002", "https://locher.ti.bfh.ch/services/assets/books/ba306ffffee4571c88a0fc1482ef4bdd3274798e-00-00.jpeg", "Web-Grafiken, Tabellen, Frames, Aufbau einer Datenbank, Dynamische Grafiken, Kryptologie mit JavaScript", "7.-10. SchuljahrDas Buch zeigt, wie mit der Einbindung von JavaScript in HTML interaktive Web-Seiten erstellt werden können. Zugleich bietet es eine problem- und anwendungsorientierte Einführung in ausgewählte Themen der Informatik (Kryptologie, Sortierverfahren, inner- und aussermathematische Probleme).]"));
		books.add(new Book("978-3-95561-740-0", "Moderne Webanwendungen mit ASP.NET MVC und JavaScript", "Manfred Steyer, Holger Schwichtenberg", 52, 560, "29.04.2014", "https://locher.ti.bfh.ch/services/assets/books/b309bce314ec81e6abb2689148493d40fc869fd0-00-00.jpeg", "ASP.NET MVC im Zusammenspiel mit Web APIs und JavaScript-Frameworks", "Manfred Steyer ist verantwortlich für den Fachbereich Software Engineering des Studienganges IT und IT-Marketing an der FH CAMPUS 02 in Graz. Zuvor war er ca. 10 Jahre lang als Projektleiter sowie Teamleiter im Bereich der Softwareentwicklung für ein großes österreichisches Systemhaus tätig. Steyer hat berufsbegleitend IT studiert und stellt sein Expertenwissen zurzeit als Buch- und Magazinautor."));
		books.add(new Book("978-3-95561-950-3", "AngularJS: Moderne Webanwendungen und Single Page Applications mit JavaScript", "Manfred Steyer, Vildan Softic", 51.9, 472, "01.04.2015", "https://locher.ti.bfh.ch/services/assets/books/40020a209ebc2f416803b5ba2c6b8ce85ee97805-00-00.jpeg", "Moderne Webanwendungen und Single Page Applications mit JavaScript", "Manfred Steyer ist verantwortlich für den Fachbereich Software Engineering des Studienganges IT und IT-Marketing an der FH CAMPUS 02 in Graz. Zuvor war er ca. 10 Jahre lang als Projektleiter sowie Teamleiter im Bereich der Softwareentwicklung für ein großes österreichisches Systemhaus tätig."));
		//books.add(new Book("978-3-86249-957-1", "JavaScript Grundlagen", "Ralph Steyer", 47.9, 208, "01.01.2020", "https://locher.ti.bfh.ch/services/assets/books/16c39d3be689dd67be088164de621b1d81d7a672-00-00.jpeg", "-", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."));
		books.add(new Book("978-3-86249-966-1", "JQuery", "Ralph Steyer", 42.9, 532, "07.05.2018", "https://locher.ti.bfh.ch/services/assets/books/5fc6dc14308458ded5ffe2dc4a282aef2ccb6d9b-00-00.jpeg", "Das universelle JavaScript-Framework für das interaktive Web und mobile Apps", "In diesem Buch werden Sie die wesentlichen Möglichkeiten lernen, wie Sie jQuery für Ihre eigenen Webapplikationen nutzen können - von einfachen Webseiten bis hin zu komplexen RIAS und mobilen Apps. <br> <br>jQuery erleichtert die Arbeit des Webprogrammierers entscheidend."));
		books.add(new Book("978-3-86490-268-0", "HTML5, JavaScript und jQuery", "Dane Cameron", 42.9, 280, "01.04.2015", "https://locher.ti.bfh.ch/services/assets/books/f118e7af1146f1867b7c43393fcab8be524a1981-00-00.jpeg", "Der Crashkurs für Softwareentwickler", "Dane Cameron lebt und arbeitet als Programmierer in Neuseeland und bietet mit seiner Firma Cisdal Software-Lösungen und -Trainings an."));
		books.add(new Book("978-3-8364-4853-6", "Konzeption & Realisierung eines browserbasierten Adventure Games mit Javascript", "Volker Ahlers", 83.9, 144, "04.12.2007", "https://assets.thalia.media/img/15115815-00-00.jpg", "Planung und Erstellung eines Prototypen in objektorientierter Praxis", "Ein auf JavaScript basierendes Spiel macht eine Installation von PlugIns,<br>denen im Allgemeinen Misstrauen entgegengebracht werden, in einem<br>Browser überflüssig. Die Idee der Realisierung eines solchen Spiels erschien daher interessant. Eine Einführung in das Für & Wider von Adventure Games<br>in Contra zu EgoShootern begleitet eine Diskussion des gesellschaftlichen<br>Einflusses dieser Medien auf die Gesellschaft."));
		books.add(new Book("978-3-86490-801-9", "JavaScript für Ungeduldige", "Cay Horstmann", 49.9, 378, "28.01.2021", "https://locher.ti.bfh.ch/services/assets/books/85ba8f65f06e96ef8dc2c9920178406087d13f3b-00-00.jpeg", "Der schnelle Einstieg in modernes JavaScript", "Cay Horstmann ist Hauptautor von Core JavaTM, Band I und II, 11. Auflage (Pear- son, 2018), Scala for the Impatient, 2. Auflage (Addison-Wesley, 2016) und Core Java SE 9 for the Impatient (Addison-Wesley, 2017). Er ist emeritierter Professor für Informatik an der San José State University (Kalifornien, USA), Java-Champion und häufiger Redner auf Konferenzen der Computerbranche."));
		books.add(new Book("978-3-86249-942-7", "Programmierung Grundlagen", "Ralph Steyer", 47.9, 170, "01.01.2021", "https://assets.thalia.media/img/md37-00-00.jpg", "mit Beispielen in Java und JavaScript (Stand 2021)", "<br>Ralph Steyer        "));
		books.add(new Book("978-1-59327-011-7", "The Web Programmer´s Desk Reference", "Joseph Issi Cohen, Lázaro Issi Cohen", 66.9, 1128, "September2004", "https://locher.ti.bfh.ch/services/assets/books/5c6fda34721a07fad91c0897477b6eb2cb637251-00-00.jpeg", "A Complete Cross-Reference to HTML, CSS, and Javascript", "One of the challenges of web programming is remembering what you can do with what, and what works with everything else. Sure, you can create a button, but can you change its color and font to match the style of your site? And are you sure it will look the same on all browsers? With The Web Programmer´s Desk Reference, you can find stuff you never knew existed, look up stuff you´re a bit rusty on, or find what´s compatible with familiar stuff so you can develop something even better."));
		books.add(new Book("978-3-8362-6255-2", "Node.js", "Sebastian Springer", 56.9, 747, "24.08.2018", "https://locher.ti.bfh.ch/services/assets/books/1ae73c13536e20d6774f340bd7d1ab478d71c4b0-00-00.jpeg", "Das umfassende Handbuch. Serverseitige Web-Applikationen mit JavaScript entwickeln", "Sebastian Springer arbeitet als Teamleiter bei der Mayflower GmbH in München. Sein Fokus liegt auf der Entwicklung von dynamischen Webapplikationen mit JavaScript und PHP."));
		books.add(new Book("978-3-8362-5696-4", "JavaScript", "Philip Ackermann", 68, 1291, "28.08.2018", "https://locher.ti.bfh.ch/services/assets/books/32febd436acfc3707269bcaeced76f082952b376-00-00.jpeg", "Das umfassende Handbuch. JavaScript lernen und verstehen. Inkl. objektorientierter und funktionaler Programmierung", "Die Fachpresse zur Vorauflage:<br><br>t3n: 'Die JavaScript-Bibel!'<br><br>eStrategy: 'Das ausführliche Werk lehrt JavaScript von der Pike auf.'<br><br>"));
		books.add(new Book("978-3-86490-127-0", "JavaScript effektiv", "David Herman", 44.9, 218, "01.11.2013", "https://locher.ti.bfh.ch/services/assets/books/8ab41a8cd1259fd5dea232a234fbd51de5dd8d0a-00-00.jpeg", "68 Dinge, die ein guter JavaScript-Entwickler wissen sollte", "David Herman ist Senior Researcher bei Mozilla Research und tätig im Ecma TC39, dem technischen Ausschuss, der sich um die Standardisierung von Java- Script kümmert. Er hat einen Bachelor in Informatik vom Grinnell College sowie einen Master- und einen Doktortitel in Informatik der Northeastern University."));
		books.add(new Book("978-3-86899-369-1", "Das Curry-Buch - Funktional programmieren lernen mit JavaScript", "Jens Ohlig, Stefanie Schirmer, Hannes Mehnert", 42.9, 208, "01.06.2013", "https://locher.ti.bfh.ch/services/assets/books/e1c46a497859a5a555cc8d3f30d83168a567f687-00-00.jpeg", "Funktional programmieren lernen mit JavaScript. Gutes Programmieren ist wie gutes Kochen", "Jens Ohlig arbeitet als Software-Entwickler bei Wikimedia Deutschland und lebt in Berlin und Bonn, aber hauptsächlich im Internet. Er ist sowohl von gutem Essen als auch freier Software begeistert und arbeitet mit wachsender Begeisterung mit JavaScript und Node.JS"));
		books.add(new Book("978-1-4493-2019-5", "JavaScript for PHP Developers", "Stoyan Stefanov", 19.9, 160, "28.02.2013", "https://locher.ti.bfh.ch/services/assets/books/fc2241ae9f6feef3b2cde79bdd8974aa1ea8bc0c-00-00.jpeg", "A Concise Guide to Mastering JavaScript", "If you want to significantly expand your web development skills beyond PHP, this practical, hands-on book teaches you ECMAScript—the core JavaScript language—from the ground up. You’ll discover some similarities between JavaScript and PHP, such as conditions and loops, but the primary focus is on JavaScript’s unique object creation, classes, prototypes, and inheritance."));
		books.add(new Book("978-1-4919-5202-3", "Javascript: The Definitive Guide", "David Flanagan", 79.9, 600, "01.06.2020", "https://locher.ti.bfh.ch/services/assets/books/8229a1b2f766fe994ec685c882d22d2d19e4da90-00-00.jpeg", "Master the World's Most-Used Programming Language", "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."));
		books.add(new Book("978-3-86490-202-4", "JavaScript objektorientiert", "Nicholas Zakas", 28.9, 122, "01.08.2014", "https://locher.ti.bfh.ch/services/assets/books/d6a12217d195631c6b8f6aa9d224ebde954f4606-00-00.jpeg", "Verständlicher, flexibler, effizienter programmieren", "Nicholas C. Zakas ist Softwareingenieur bei Box und widmet sich als bekannter Redner und Autor den neuesten Best Practices in der JavaScript-Entwicklung. Seine Kenntnisse konnte er während seiner fünf Jahre bei Yahoo! verfeinern, wo er als leitender Frontend-Ingenieur für die Yahoo!-Homepage tätig war. Er hat mehrere Bücher geschrieben, darunter Maintainable JavaScript (O’Reilly Media, 2012) und Professional JavaScript for Web Developers (Wrox, 2012)."));
		books.add(new Book("978-3-658-05443-4", "Objektorientierte Programmierung mit JavaScript", "Jörg Bewersdorff", 36.9, 360, "28.05.2014", "https://locher.ti.bfh.ch/services/assets/books/eb40ca8446a308217f9e0bd5e218a333144b27a0-00-00.jpeg", "Direktstart für Einsteiger", "Dr. Jörg Bewersdorff promovierte im Fach Mathematik und veröffentlichte bereits drei mathematische Fachbücher bei Springer. Er ist seit über einem Jahrzehnt Geschäftsführer der Firmen MEGA Web und GeWeTe, die u. a. Internet-Terminals und internetbasierte Kassenautomaten herstellen."));
		books.add(new Book("978-3-519-00381-6", "Kompakt im Doppelpack: HTML und JavaScript", "Dietrich Baumgarten", 44.9, 175, "27.11.2002", "https://locher.ti.bfh.ch/services/assets/books/889311259faa936a5e2c569c987c59d1d242fa33-00-00.jpeg", "Webdesign für Einsteiger", "Prof. Dr. Dietrich Baumgarten, Fachhochschule Darmstadt<br><br>"));
		books.add(new Book("978-3-86899-388-2", "JavaScript - kurz & gut", "David Flanagan", 21.9, 277, "01.07.2012", "https://locher.ti.bfh.ch/services/assets/books/a960838ab4a03ee2f444da6d3be21e13932db3f1-00-00.jpeg", "", "Zur vorherigen Auflage: 'In dem vorliegenden Buch JavaScript - kurz & gut aus O'Reillys Taschenbibliothek bekommt man einen schnellen Überblick über das, was JavaScript eigentlich ist. [...] Das Buch ist ein Muss für jeden Webentwickler, der seine Seite professionell gestalten will. Ein so fundiertes Nachschlagewerk nimmt nicht viel Platz weg und erleichtert die alltägliche Arbeit.' - Vera Schott, Media-Mania.de, September 2005"));
		books.add(new Book("978-3-95561-866-7", "JavaScript-Programmierung von Kopf bis Fuß", "Eric Freeman, Elisabeth Robson", 63.9, 698, "30.10.2014", "https://locher.ti.bfh.ch/services/assets/books/f2b962968c9a2a324c94075997eb153cebf2d757-00-00.jpeg", "", "Eric Freeman ist Informatiker und begeistert sich für Software- und Medienarchitektur. Er hat gerade vier Jahre in einem Traumjob bei Disney hinter sich, wo er ein Projekt zu Breitbandinternet und drahtloser Übertragung geleitet hat; jetzt arbeitet er wieder als Autor, programmiert coole Software und betätigt sich als Java- und Mac-Hacker."));
		books.add(new Book("978-3-96009-157-8", "JavaScript - Das Handbuch für die Praxis", "David Flanagan", 56.9, 748, "22.04.2021", "https://locher.ti.bfh.ch/services/assets/books/505b298d45885ac6d81917988ed41682c7332d5f-00-00.jpeg", "Meistern Sie die beliebte Sprache für Web und Node.js", "David Flanagan programmiert seit 1995 mit JavaScript und schreibt seitdem über die Sprache. Er besitzt einen Abschluss in Computer Science und Engineering des Massachusetts Institute of Technology und arbeitet als Softwareingenieur bei VMware."));
		books.add(new Book("978-1-119-03863-4", "Web Design with Html, Css, JavaScript and Jquery Set", "Jon Duckett", 92.9, 1152, "29.09.2014", "https://locher.ti.bfh.ch/services/assets/books/354a7a074df4f7e29300b64f7f725b9cfc37b964-00-00.jpeg", "", "En 1921, à Caltanissetta en Sicile, Lillino Grattuso, jeune sympathisant fasciste, est tué par balle -une balle perdue- lors d'une bagarre de rue, la nuit. Michele Lopardo, sympathisant communiste, est pour les autorités le coupable tout désigné, alors que Grattuso est élevé malgré lui à la dignité de seul martyr fasciste de Sicile."));
		books.add(new Book("978-93-86768-64-3", "JavaScript", "Archana Devi, Chellaprabha, Shriram K. Vasudevan, Sunandhini Muralidharan", 102, 168, "30.05.2020", "https://assets.thalia.media/img/md37-00-00.jpg", "", "JavaScript helps users to create exciting web pages that employ the power of JavaScript to provide functionality. It allows dynamic content to get executed in a webpage. This book explores all the features of JavaScript to create an interactive web page."));
		books.add(new Book("978-0-672-32880-0", "JavaScript Phrasebook", "Christian Wenz", 23.9, 272, "01.08.2006", "https://locher.ti.bfh.ch/services/assets/books/0620ee5bec1f2c139208bf929ed8b879e3f6896f-00-00.jpeg", "Essential Code and Commandos", "Christian Wenz ist Autor, Trainer und Berater mit Schwerpunkt Webentwicklung und Sicherheit. Er ist Autor oder Koautor von über 50 Büchern, hat zahlreiche Fachartikel verfasst und spricht regelmässig auf Entwicklerkonferenzen im In- und Ausland. Er steht in den Credits des Mozilla-Browsers, besitzt diverse Macromedia-, Zend- und Microsoft-Zertifizierungen, ist Gründungsmitglied des PHP Security Consortiums und wurde als Microsoft MVP für ASP/ASP.NET ausgezeichnet.Als Teilhaber der Webagentur Arrabiata Solutions GmbH realisiert er Web- und Intranetprojekte, führt Sicherheitsprüfungen durch und entwickelt AJAX-Anwendungen."));
		books.add(new Book("978-0-538-46813-8", "Gosselin, D: JavaScript", "Don Gosselin", 194, 720, "11.02.2010", "https://locher.ti.bfh.ch/services/assets/books/2b7070d669eeb954db2f94b81668702c1ceb1e02-00-00.jpeg", "International Edition", "Now in its fifth edition, JAVASCRIPT, International Edition guides beginning programmers through Web application development using the JavaScript programming language. As with previous editions of this book, Don Gosselin introduces key Web authoring techniques with a strong focus on industry application. A real-world project, similar to what students would encounter in a professional setting, is developed throughout each chapter. "));
		books.add(new Book("978-1-84078-362-9", "JavaScript in Easy Steps", "Mike McGrath", 28.9, 192, "Mai2009", "https://locher.ti.bfh.ch/services/assets/books/075c0dfd37228017d569e27ff29378e363d83bf0-00-00.jpeg", "", "4th edition. Instructs how to add functionality (logic) and dynamic effects (DHTML) to web pages.<br>"));
		books.add(new Book("978-0-672-33734-5", "JQuery and JavaScript in 24 Hours", "Brad Dayley", 42.9, 450, "06.01.2014", "https://locher.ti.bfh.ch/services/assets/books/088a32eba12d4299bdfc40f08d20d816000da781-00-00.jpeg", "", "Brad Dayley is a senior software engineer with more than 20 years of experience developing enterprise applications. He has used HTML/CSS, JavaScript, and jQuery extensively to develop a wide array of web pages, ranging from enterprise application interfaces to sophisticated, rich Internet applications, to smart interfaces for mobile web services. He is the author of Python Phrasebook and jQuery and JavaScript Phrasebook."));
		books.add(new Book("978-1-118-02622-9", "HTML, CSS, and JavaScript Mobile Development For Dummies", "Bill Harrel", 47.9, 408, "20.09.2011", "https://locher.ti.bfh.ch/services/assets/books/7bef9d64410b108e6828dbd9daac473749141073-00-00.jpeg", "", "William Harrel has nearly 25 years of digital design experience. He was one of the pioneers of publishing on desktop computers, starting with the very first digital design and graphics programs, PageMaker and Photoshop. Like so many of the early 'desktop publishers,' with the emergence of the World Wide Web, he found that making the transition to web design was the next logical step. His design fi rm has designed hundreds of websites, Flash websites, and electronic "));
		books.add(new Book("978-1-4493-2955-6", "Appcelerator Titanium: Up and Running: Building Native IOS and Android Apps Using JavaScript", "John Anderson", 29.9, 154, "22.03.2013", "https://locher.ti.bfh.ch/services/assets/books/4d5da6f8c72785305fe65a79077a38b27264b73d-00-00.jpeg", "", "Im Browser kompiliert, interpretiert und führt die JavaScript-Engine JavaScript-Code aus, der sich auf einer Webseite befindet. Es bietet Speicherverwaltung, eine Zusammenstellung von JIT, Systemtypisierung usw. In jedem Browser sind zahlreiche JavaScript-Engines eingebettet."));
		books.add(new Book("978-3-86899-797-2", "Einführung in Node.js", "Tom Hughes-Croucher, Mike Wilson", 48.9, 194, "01.10.2012", "https://locher.ti.bfh.ch/services/assets/books/a1f29c2db665b35db98999c12a14005a76e2d087-00-00.jpeg", "Skalierbarer, serverseitiger Code in JavaScript", "'Wer mit Node.js serverseitiges JavaScript einsetzen möchte, findet mit diesem Standardwerk einen umfangreichen Fundus.' - t3n, 3/2013 '[W]eckt Lust, die Erstellung einer interaktiven Webapplikation mit Node.js in Angriff zu nehmen.' - Javamagazin, 7/2013"));
		books.add(new Book("978-3-86490-050-1", "CoffeeScript", "Andreas Schubert", 14.9, 188, "01.10.2014", "https://locher.ti.bfh.ch/services/assets/books/576dd73632e947fee361c2456323e30b7225cf93-00-00.jpeg", "Die Alternative zu JavaScript - eine kompakte Einführung", "Andreas Schubert ist Systemadministrator bei der MATHEMA Software GmbH in Erlangen. Neben der Betreuung heterogener Netzwerke beschäftigt er sich mit Ruby, Ruby on Rails und CoffeeScript."));
		books.add(new Book("978-3-8362-8523-0", "Einstieg in JavaScript", "Thomas Theis", 42.9, 517, "30.06.2021", "https://locher.ti.bfh.ch/services/assets/books/bf878164e24011f722a25592e7c844bb371c20a4-00-00.jpeg", "Dynamische Webseiten erstellen. Inkl. Ajax, jQuery, Onsen UI u. v. m.", "Lernen Sie Schritt für Schritt die Grundlagen der modernen JavaScript-Programmierung. Das Buch führt Sie in alle relevanten Bereiche ein: HTML und CSS, Objekte, anonyme Funktionen, Ereignisbehandlung, jQuery und Ajax. Zahlreiche anschauliche Beispielanwendungen erleichtern das Verständnis und dienen Ihnen als Vorlage für Ihre eigenen Projekte. Schon bald entwickeln Sie anspruchsvolle interaktive Programme für Ihre Website."));
		books.add(new Book("978-3-87439-902-9", "Generative Gestaltung", "Benedikt Gross, Hartmut Bohnacker, Julia Laub, Claudius Lazzeroni", 62.9, 256, "01.03.2018", "https://locher.ti.bfh.ch/services/assets/books/94af344c300d634a353ded9ec038f3e20ced3ec2-00-00.jpeg", "Creative Coding im Web Entwerfen, Programmieren und Visualisieren mit Javascript in p5.js", "Keine Angst vor Coding und Programmieren!<br>Dank generativer Gestaltung können Sie Ideen realisieren, von denen Sie bislang nur geträumt haben. Einfach und effizient können Sie eigene Kreativ-Tools mit der browser-basierten Programmierung in p5.js erstellen. Mit diesen individuellen Werkzeugen generieren Sie automatisch eine Vielzahl visueller Varianten, auf deren Basis Sie die besten Lösungsansätze wählen."));
		books.add(new Book("978-3-96645-036-2", "JavaScript Programmieren für Einsteiger", "Paul Fuchs", 29.9, 376, "27.04.2019", "https://locher.ti.bfh.ch/services/assets/books/032548ad1b793d6c31ecab7b95b6fd94ae7e9ac3-00-00.jpeg", "Der leichte Weg zum JavaScript-Experten", "'Wenn es um dynamische Webseiten geht, liegt JavaScript als Werkzeug in der Entwicklergunst weit vorn. Paul Fuchs bietet Anfängern einen sehr niedrigschwelligen Einstieg, spart aber auch komplexe Themen wie Event-Behandlung, Ajax, CSS und die JQuery-Bibliothek nicht aus.' --c't 15/19<br><br>Der leichte Weg zum JavaScript-Experten!<br><br>JavaScript ist die wichtigste clientseitige Programmiersprache zur Erstellung moderner dynamischer Webseiten, und zudem überaus einfach zu erlernen. Mit diesem Buch lernen Sie das Programmieren mit JavaScript verständlich und praxisorientiert, ohne dass dabei Vorkenntnisse vonnöten wären."));
		books.add(new Book("978-3-8362-7369-5", "Programmieren lernen mit JavaScript", "Stephan Elter", 36.9, 391, "22.11.2019", "https://locher.ti.bfh.ch/services/assets/books/93cbd5ce0350117b0652df45ccc7eecdec3d8759-00-00.jpeg", "Der kinderleichte Einstieg in die Programmierung. Mit vielen Übungen, Spielen und Beispielen", "Entdecke mit JavaScript die Sprache, die hinter fast jeder Webseite steckt, und programmiere Spiele und Anwendungen, die einfach Spass machen. Steig direkt ein, du brauchst nur deinen Computer und dieses Buch. Es zeigt dir alles von den ersten Befehlen bis zu Grafik und Animation – Schritt für Schritt und an vielen Beispielen. Deine Programme kannst du direkt im Browser laufen lassen und leicht an Freunde weitergeben, ganz unabhängig vom Betriebssystem. Ran an die Tasten, fertig, los!"));

		return books;
	}
}
